# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86d2ef9537f7acb3078503c0e135dcd9c004ffdf843cb60c910228395909a76bd8fcee266a307e8d145e4b3740f05bd25f2653e25ed65eb0689e6bb1ed805a39

test:
  secret_key_base: 36f683992050493b1a33805fb455a7a9bfdd537dfdaced114c9c2b93433f1d1751d41efa68ca3060a275b708b2bedebfb19a6b2430c34d3118e6bf391f0c5a8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
